# Generated by Django 5.1.1 on 2024-09-19 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0002_alter_artist_nacionality"),
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release Date"
                    ),
                ),
                (
                    "resume",
                    models.TextField(blank=True, null=True, verbose_name="Resume"),
                ),
                (
                    "artists",
                    models.ManyToManyField(related_name="songs", to="artists.artist"),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="genres.genre"
                    ),
                ),
            ],
        ),
    ]
