# Generated by Django 5.1.1 on 2024-09-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="Birthday"),
                ),
                (
                    "nacionality",
                    models.CharField(
                        blank=True,
                        choices=[("USA", "Estados Unidos"), ("BRAZIL", "Brasil")],
                        max_length=100,
                        null=True,
                        verbose_name="Nationality",
                    ),
                ),
            ],
        ),
    ]
