# Generated by Django 5.1.1 on 2024-09-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="nacionality",
            field=models.CharField(
                blank=True,
                choices=[("USA", "United States of America"), ("BR", "Brazil")],
                max_length=100,
                null=True,
                verbose_name="Nationality",
            ),
        ),
    ]
