# Generated by Django 5.1.1 on 2024-09-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0002_alter_artist_nacionality"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="nacionality",
        ),
        migrations.AddField(
            model_name="artist",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nationality"
            ),
        ),
    ]
